<?php

$title = 'Nova Categoria';
$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php
$form->setAttribute('action', $this->url('category_add', ['action' => 'handle']));
$form->prepare();

echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id_categoria_produto'));
    echo $this->formRow($form->get('nome_categoria'));
    echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();