<?php
$title = 'Categorias de Produtos';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('category_add', ['action' => 'handle']); ?>">Nova Categoria</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($categories as $category) : ?>
            <tr>
                <td><?= $this->escapeHtml($category->id_categoria_produto) ?></td>
                <td><?= $this->escapeHtml($category->nome_categoria) ?></td>
                <td>
                    <a href="<?= $this->url('category_edit', ['action' => 'handle', 'id' => $category->id_categoria_produto]) ?>">Editar</a>
                    <a href="<?= $this->url('category_delete', ['action' => 'handle', 'id' => $category->id_categoria_produto]) ?>">Deletar</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>