<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?= $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?= $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>ID</th>
     <th>Categoria</th>
     <th>Data/Horario</th>
     <th>Nome</th>
     <th>Preço</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?= $this->escapeHtml($album->title);?></td>
     <td><?= $this->escapeHtml($album->artist);?></td>
     <td><?= $this->escapeHtml($album->artist);?></td>
     <td><?= $this->escapeHtml($album->artist);?></td>
     <td><?= $this->escapeHtml($album->artist);?></td>
     <td>
         <a href="<?= $this->url('album',
             array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
         <a href="<?= $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>